nlsw_set_difference

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -20886,10 +20886,13 @@ main() {
 
     if [ "$Cleanup" ] ; then
         # --cleanup: Clean up cache and orphaned x11docker containers
-        check_optionset \
-            "--cleanup" \
-            "$(grep -v -E -- '--cleanup|--backend' <<< "$g_AllAvailableLongOptions")" \
-            || true
+        # The only option comptible with --cleanup is --backend.
+        check_optionset                           \
+            "--cleanup"                           \
+            "$( nlsw_set_difference               \
+                   "$g_AllAvailableLongOptions"   \
+                    '--cleanup --backend'         \
+              )" || true
         #
         cleanup
         finish
