check_vt()

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -5408,7 +5408,7 @@ calculate_floor_a_per_b() {
 #                               (also option --size)
 check_screensize() {
     local Line="" Xrandroutput=""
-    local mysed
+    local mysed=""
     local ERE1=""
     local ERE2=""
     local monitorname_ERE=""
@@ -5601,91 +5601,148 @@ check_screensize() {
             #
             Modeline="$( echo "$Modeline" | sed -E -e "s|${Modeline_ERE}|\"\\1\"|" )"
         fi
-  fi
+    fi
 
-  verbose "Virtual screen size: $Screensize"
-  verbose "Physical screen size:
-  $(grep Screen <<< "$Xrandroutput" ||:)"
+    verbose "Virtual screen size: $Screensize"
+    verbose "Physical screen size:${NEWLINE}  $( grep Screen <<< "$Xrandroutput" || : )"
 
-  # create set of Modelines if needed
-  case "$Xserver" in
-    --xpra|--xpra2|--xvfb|--xwayland|--weston-xwayland|--kwin-xwayland) xtool --check cvt && Modelinefile="$(create_modelinefile "${Maxxaxis}x${Maxyaxis}")" ;;
-  esac
+    # Create set of Modelines if needed
+    case "$Xserver" in
+        --xpra|--xpra2|--xvfb|--xwayland|--weston-xwayland|--kwin-xwayland)
+            if xtool --check cvt ; then
+                Modelinefile="$( create_modelinefile "${Maxxaxis}x${Maxyaxis}" )"
+            fi
+            ;;
+    esac
 
-  return 0
-}
+    return 0
+} # check_screensize()
 
-check_vt() {                    # option --xorg: find free vt / tty
-  local Line= Ttyinuse=
+#
+# function check_vt() : option --xorg: find free vt / tty
+#
+# - On success, global Newxvt contains the number of the chosen tty.
+#
+# - If on entry Newxvt is not empty and is not "auto", just return 0
+#   without testing anything.
+#
+check_vt() {
+    local Line=""
+    local Ttyinuse=""
 
-  # if started from console, use current tty
-  case "$Newxvt" in
-    "")
-      tty -s && [ "$Runsonconsole" = "yes" ] && {
-        Newxvt="${Newxvt#/dev/tty}"
-      }
-    ;;
-    auto) Newxvt="" ;;
-    *)    return 0 ;;
-  esac
+    # If started from console, use current tty
+    case "$Newxvt" in
+        "")
+            if tty -s && [ "$Runsonconsole" = "yes" ] ; then
+                #
+                # FIXME: In this branch we know Newxvt is "", so the
+                #        "/dev/tty" prefix is not here.
+                #
+                #         Why are we trying to remove it?
+                #         Did we lose a `Newxvt="$(tty)"` ?
+                # 
+                #
+                Newxvt="${Newxvt#/dev/tty}"
+            fi
+            ;;
+        auto) Newxvt="" ;;
+        *)
+            # If neither "", nor "auto", we just return success.
+            return 0
+            ;;
+    esac
 
-  # check ttys currently in use
-  [ "$Newxvt" ] || {
-    for Line in $(find /sys/class/vc/vcsa*); do
-      Ttyinuse="$Ttyinuse ${Line#/sys/class/vc/vcsa} "
-    done
-    debugnote "check_vt(): TTYs currently known to kernel: $Ttyinuse"
-  }
+    # Check ttys currently in use
+    if [ -z "$Newxvt" ] ; then
+        for Line in $(find /sys/class/vc/vcsa*); do
+            #
+            # Note "/sys/class/vc/vcsa" exists, and will be lost on
+            # the next line. Probably correspond to "current" vt.
+            #
+            Ttyinuse="$Ttyinuse ${Line#/sys/class/vc/vcsa} "
+        done
+        debugnote "check_vt(): TTYs currently known to kernel: $Ttyinuse"
+    fi
 
-  [ "$Newxvt" ] && grep -q " $Newxvt " <<< "$Ttyinuse" && warning "TTY $Newxvt seems to be already in use."
+    # FIXME: Newxvt is always empty here.
+    if [ -n "$Newxvt" ] && grep -q " $Newxvt " <<< "$Ttyinuse" ; then
+        warning "TTY $Newxvt seems to be already in use."
+    fi
 
-  # try to find free tty within range of 8..12
-  [ "$Newxvt" ] || {
-    for ((Newxvt=8 ; Newxvt<=12 ; Newxvt++)) ; do
-      grep -q " $Newxvt " <<< "$Ttyinuse" || break
-    done
-  }
+    # Try to find free tty within range of 8..12
+    if [ -z "$Newxvt" ] ; then
+        for ((Newxvt=8 ; Newxvt<=12 ; Newxvt++)) ; do
+            if ! grep -q " $Newxvt " <<< "$Ttyinuse" ; then  break ; fi
+        done
+    fi
 
-  # try to find free tty within range of 1..7
-  [ "$Newxvt" ] || {
-    for ((Newxvt=1 ; Newxvt<=7 ; Newxvt++)) ; do
-      grep -q " $Newxvt " <<< "$Ttyinuse" || break
-    done
-  }
+    # Try to find free tty within range of 1..7
+    if [ -z "$Newxvt" ] ; then
+        for ((Newxvt=1 ; Newxvt<=7 ; Newxvt++)) ; do
+            if ! grep -q " $Newxvt " <<< "$Ttyinuse" ; then break ; fi
+        done
+    fi
 
-  # try to find free tty with fgconsole. Fails without privileges within X.
-  [ "$Newxvt" ] || Newxvt="$(fgconsole --next-available 2>/dev/null)"
-  [ "$Newxvt" ] || Newxvt="$(fgconsole --next-available 2>/dev/null < "/dev/tty${XDG_VTNR:-}")"
+    # Try to find free tty with fgconsole. Fails without privileges
+    # within X.
+    #
+    if [ -z "$Newxvt" ] ; then
+        Newxvt="$(fgconsole --next-available 2>/dev/null)"
+    fi
+    #
+    if [ -z "$Newxvt" ] ; then
+        # XDG_VTNR is an environment variable that holds the number of
+        # the virtual terminal (TTY) where the current graphical
+        # session is running.
+        Newxvt="$(fgconsole --next-available 2>/dev/null < "/dev/tty${XDG_VTNR:-}")"
+        # Note: man fgconsole does not mention stdin. But it
+        # presumably works by checking the tty of its stdin.
+    fi
 
-  # try to find free tty within range of 13..63
-  [ "$Newxvt" ] || {
-    for ((Newxvt=13 ; Newxvt<=63 ; Newxvt++)) ; do
-      grep -q " $Newxvt " <<< "$Ttyinuse" || break
-    done
-  }
+    # Try to find free tty within range of 13..63
+    if [ -z "$Newxvt" ] ; then
+        for ((Newxvt=13 ; Newxvt<=63 ; Newxvt++)) ; do
+            if ! grep -q " $Newxvt " <<< "$Ttyinuse" ; then break ; fi
+        done
+    fi
 
-  [ "$Newxvt" ] || error "Could not identify a free tty for --xorg.
-  You can specify a desired tty number N with option --vt=N."
+    if [ -z "$Newxvt" ] ; then
+        error "$(trim_to_bar \
+               "|Could not identify a free tty for --xorg.
+                |  You can specify a desired tty number N with option --vt=N."
+                )"
+    fi
 
-  [ "${XDG_VTNR:-}" ] && [ "$Hostdisplay$Hostwaylandsocket" ] && note "Current X server $Hostdisplay runs on tty ${XDG_VTNR:-}.
-  Access it with [CTRL][ALT][F${XDG_VTNR:-}]."
+    if [ -n "${XDG_VTNR:-}" ] && [ -n "$Hostdisplay$Hostwaylandsocket" ] ; then
+        note "$(trim_to_bar \
+              "|Current X server $Hostdisplay runs on tty ${XDG_VTNR:-}.
+               |  Access it with [CTRL][ALT][F${XDG_VTNR:-}]."
+               )"
+    fi
 
-  [ "${Newxvt:-999}" -gt "12" ] && {
-    fgconsole --next-available 1>/dev/null 2>/dev/null || note "Could not check for a free tty below or equal to 12.
-  Would need to use command fgconsole for a better check.
-  Possibilities:
-  1.) Run x11docker as root.
-  2.) Add user to group tty (not recommended, may be insecure).
-  3.) Use display manager gdm3.
-  4.) Run x11docker directly from console."
-    note "To access X on tty$Newxvt, use command 'chvt $Newxvt'"
-  } || {
-    note "New X server $Xserver $Newdisplay will run on tty $Newxvt.
-  Access it with [CTRL][ALT][F$Newxvt]."
-  }
+    if [ "${Newxvt:-999}" -gt "12" ] ; then
+        if ! fgconsole --next-available 1>/dev/null 2>/dev/null ; then
+            note "$(trim_to_bar \
+                  "|Could not check for a free tty below or equal to 12.
+                   |  Would need to use command fgconsole for a better check.
+                   |  Possibilities:
+                   |  1.) Run x11docker as root.
+                   |  2.) Add user to group tty (not recommended, may be insecure).
+                   |  3.) Use display manager gdm3.
+                   |  4.) Run x11docker directly from console."
+                   )"
+        fi
+        note "To access X on tty$Newxvt, use command 'chvt $Newxvt'"
+    else
+        note "$(trim_to_bar \
+              "|New X server $Xserver $Newdisplay will run on tty $Newxvt.
+               |  Access it with [CTRL][ALT][F$Newxvt]."
+               )"
+    fi
 
-  return 0
-}
+    return 0
+} # check_vt()
+
 
 check_xcontainer() {            # option --xc: check backend, rootless and image x11docker/xserver
   local Auto= Fail=
