use +=

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -1225,7 +1225,7 @@ watchpidlist() {
                 #
                 ListOfLines=""
                 for Line in $Watchpidlist; do
-                    ListOfLines="${ListOfLines}$(pspid "$Line" || echo "(pid $Line not found)")" ;
+                    ListOfLines+="$(pspid "$Line" || echo "(pid $Line not found)")" ;
                 done
                 debugnote "watchpidlist(): Watching pids:${NEWLINE}${ListOfLines}"
             fi
