rootrc_prepare_init_sysvinit

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -15802,111 +15802,119 @@ rootrc_prepare_init_systemd() {
     return 0
 } # end rootrc_prepare_init_systemd()
 
-
+# Function: rootrc_prepare_init_sysvinit
+#
 rootrc_prepare_init_sysvinit() {
-  echo "
-# --init=sysvinit
-# Adding x11docker start command to rc.local
-sed -i '/exit 0/d' /etc/rc.local
+    trim_to_bar "|
+                 |# --init=sysvinit
+                 |# Adding x11docker start command to rc.local
+                 |sed -i '/exit 0/d' /etc/rc.local
+                 |
+                 |trim_to_mark \"|
+                 |               |if ! /usr/local/bin/x11docker-agetty ; then
+                 |               |    echo \\\"x11docker: Exit code of x11docker-agetty: \\\$?\\\"
+                 |               |fi
+                 |               |echo 'x11docker: rc.local sends shutdown -h now'
+                 |               |shutdown -h now
+                 |               |exit 0
+                 |               |\" >> /etc/rc.local
+                 |
+                 |chmod +x /etc/rc.local
+                 |
+                 |# DBus service
+                 |trim_to_mark '|#!/bin/sh
+                 |              |### BEGIN INIT INFO
+                 |              |# Provides:          dbus
+                 |              |# Required-Start:    \$remote_fs \$syslog
+                 |              |# Required-Stop:     \$remote_fs \$syslog
+                 |              |# Default-Start:     2 3 4 5
+                 |              |# Default-Stop:
+                 |              |# Short-Description: D-Bus systemwide message bus
+                 |              |# Description:       D-Bus is a simple interprocess messaging system, used
+                 |              |#                    for sending messages between applications.
+                 |              |### END INIT INFO
+                 |              |# -*- coding: utf-8 -*-
+                 |              |# Debian init.d script for D-BUS
+                 |              |# Copyright © 2003 Colin Walters <walters@debian.org>
+                 |              |# Copyright © 2005 Sjoerd Simons <sjoerd@debian.org>
+                 |              |#
+                 |              |DAEMON=/usr/bin/dbus-daemon
+                 |              |UUIDGEN=/usr/bin/dbus-uuidgen
+                 |              |UUIDGEN_OPTS=--ensure
+                 |              |NAME=dbus
+                 |              |DAEMONUSER=messagebus
+                 |              |PIDDIR=/var/run/dbus
+                 |              |PIDFILE=\"\$PIDDIR/pid\"
+                 |              |DESC=\"system message bus\"
+                 |              |#
+                 |              |test -x \$DAEMON || exit 1
+                 |              |. /lib/lsb/init-functions
+                 |              |# Source defaults file; edit that file to configure this script.
+                 |              |PARAMS=""
+                 |              |if [ -e /etc/default/dbus ]; then
+                 |              |  . /etc/default/dbus
+                 |              |fi
+                 |              |create_machineid() {
+                 |              |  # Create machine-id file
+                 |              |  if [ -x \$UUIDGEN ]; then
+                 |              |    \$UUIDGEN \$UUIDGEN_OPTS
+                 |              |  fi
+                 |              |}
+                 |              |start_it_up() {
+                 |              |  [ -d \$PIDDIR ] || {
+                 |              |    mkdir -p \$PIDDIR
+                 |              |    chown \$DAEMONUSER \$PIDDIR
+                 |              |    chgrp \$DAEMONUSER \$PIDDIR
+                 |              |  }
+                 |              |  mountpoint -q /proc/ || {
+                 |              |    log_failure_msg \"Cannot start \$DESC - /proc is not mounted\"
+                 |              |    return 1
+                 |              |  }
+                 |              |  [ -e \$PIDFILE ] && {
+                 |              |    \$0 status > /dev/null && {
+                 |              |      log_success_msg \"\$DESC already started; not starting.\"
+                 |              |      return 0
+                 |              |    }
+                 |              |    log_success_msg \"Removing stale PID file \$PIDFILE.\"
+                 |              |    rm -f \$PIDFILE
+                 |              |  }
+                 |              |  create_machineid
+                 |              |  log_daemon_msg \"Starting \$DESC\" \"\$NAME\"
+                 |              |  start-stop-daemon --start --quiet --pidfile \$PIDFILE
+                 |              : --exec \$DAEMON -- --system \$PARAMS
+                 |              |  log_end_msg \$?
+                 |              |}
+                 |              |shut_it_down() {
+                 |              |  log_daemon_msg \"Stopping \$DESC\" \"\$NAME\"
+                 |              |  start-stop-daemon --stop --retry 5 --quiet --oknodo
+                 |              : --pidfile \$PIDFILE --user \$DAEMONUSER
+                 |              |  log_end_msg \$?
+                 |              |  rm -f \$PIDFILE
+                 |              |}
+                 |              |reload_it() {
+                 |              |  create_machineid
+                 |              |  log_action_begin_msg \"Reloading \$DESC config\"
+                 |              |  dbus-send --print-reply --system --type=method_call
+                 |              : --dest=org.freedesktop.DBus / org.freedesktop.DBus.ReloadConfig > /dev/null
+                 |              |  log_action_end_msg \$?
+                 |              |}
+                 |              |case \$1 in
+                 |              |  start) start_it_up ;;
+                 |              |  stop)  shut_it_down ;;
+                 |              |  reload|force-reload) reload_it ;;
+                 |              |  restart)
+                 |              |    shut_it_down
+                 |              |    start_it_up
+                 |              |  ;;
+                 |              |  status) status_of_proc -p \$PIDFILE \$DAEMON \$NAME && exit 0 || exit \$? ;;
+                 |              |esac
+                 |              |' > /etc/init.d/dbus
+                 |chmod +x /etc/init.d/dbus
+                 |"
+    #
+    return 0
+} # end rootrc_prepare_init_sysvinit
 
-echo \"
-/usr/local/bin/x11docker-agetty || echo \\\"x11docker: Exit code of x11docker-agetty: \\\$?\\\"
-echo 'x11docker: rc.local sends shutdown -h now'
-shutdown -h now
-exit 0
-\" >> /etc/rc.local
-
-chmod +x /etc/rc.local
-
-# DBus service
-echo '#!/bin/sh
-### BEGIN INIT INFO
-# Provides:          dbus
-# Required-Start:    \$remote_fs \$syslog
-# Required-Stop:     \$remote_fs \$syslog
-# Default-Start:     2 3 4 5
-# Default-Stop:
-# Short-Description: D-Bus systemwide message bus
-# Description:       D-Bus is a simple interprocess messaging system, used
-#                    for sending messages between applications.
-### END INIT INFO
-# -*- coding: utf-8 -*-
-# Debian init.d script for D-BUS
-# Copyright © 2003 Colin Walters <walters@debian.org>
-# Copyright © 2005 Sjoerd Simons <sjoerd@debian.org>
-#
-DAEMON=/usr/bin/dbus-daemon
-UUIDGEN=/usr/bin/dbus-uuidgen
-UUIDGEN_OPTS=--ensure
-NAME=dbus
-DAEMONUSER=messagebus
-PIDDIR=/var/run/dbus
-PIDFILE=\"\$PIDDIR/pid\"
-DESC=\"system message bus\"
-#
-test -x \$DAEMON || exit 1
-. /lib/lsb/init-functions
-# Source defaults file; edit that file to configure this script.
-PARAMS=""
-if [ -e /etc/default/dbus ]; then
-  . /etc/default/dbus
-fi
-create_machineid() {
-  # Create machine-id file
-  if [ -x \$UUIDGEN ]; then
-    \$UUIDGEN \$UUIDGEN_OPTS
-  fi
-}
-start_it_up() {
-  [ -d \$PIDDIR ] || {
-    mkdir -p \$PIDDIR
-    chown \$DAEMONUSER \$PIDDIR
-    chgrp \$DAEMONUSER \$PIDDIR
-  }
-  mountpoint -q /proc/ || {
-    log_failure_msg \"Cannot start \$DESC - /proc is not mounted\"
-    return 1
-  }
-  [ -e \$PIDFILE ] && {
-    \$0 status > /dev/null && {
-      log_success_msg \"\$DESC already started; not starting.\"
-      return 0
-    }
-    log_success_msg \"Removing stale PID file \$PIDFILE.\"
-    rm -f \$PIDFILE
-  }
-  create_machineid
-  log_daemon_msg \"Starting \$DESC\" \"\$NAME\"
-  start-stop-daemon --start --quiet --pidfile \$PIDFILE --exec \$DAEMON -- --system \$PARAMS
-  log_end_msg \$?
-}
-shut_it_down() {
-  log_daemon_msg \"Stopping \$DESC\" \"\$NAME\"
-  start-stop-daemon --stop --retry 5 --quiet --oknodo --pidfile \$PIDFILE --user \$DAEMONUSER
-  log_end_msg \$?
-  rm -f \$PIDFILE
-}
-reload_it() {
-  create_machineid
-  log_action_begin_msg \"Reloading \$DESC config\"
-  dbus-send --print-reply --system --type=method_call --dest=org.freedesktop.DBus / org.freedesktop.DBus.ReloadConfig > /dev/null
-  log_action_end_msg \$?
-}
-case \$1 in
-  start) start_it_up ;;
-  stop)  shut_it_down ;;
-  reload|force-reload) reload_it ;;
-  restart)
-    shut_it_down
-    start_it_up
-  ;;
-  status) status_of_proc -p \$PIDFILE \$DAEMON \$NAME && exit 0 || exit \$? ;;
-esac
-' > /etc/init.d/dbus
-chmod +x /etc/init.d/dbus
-"
-  return 0
-}
 rootrc_setup_user() {
   local Line
 
