main()

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -15133,7 +15133,7 @@ main() {
         trap 'traperror $? $LINENO $BASH_LINENO "$BASH_COMMAND" $(printf "::%s" ${FUNCNAME[@]})'  ERR
     fi
 
-    if [ -n "$Containeruserpassword" ] ; then  {
+    if [ -n "$Containeruserpassword" ] ; then
         #
         # --password  [=WORD]   Change container user password and exit.
         #
@@ -15149,49 +15149,71 @@ main() {
         return 0
     fi
 
-  debugnote "x11docker version $Version"
-  check_host                     # get some infos about host system
-  check_options_arguments        # check for valid arguments
-  check_hostuser                 # find unprivileged host user                    # --hostuser
-  check_console                  # check if running on console
-  create_cachefiles              # create cache files owned by unprivileged user  # --cachebasedir
-  setup_verbosity                # create [and show] summary logfile              # --verbose
-  check_containeruser            # unprivileged user in container                 # --user
-  check_containerhomebasedir     # check base dir for --home and possible rootfs  # --homebasedir
+    debugnote "x11docker version $Version"
+    check_host                     # get some infos about host system
+    check_options_arguments        # check for valid arguments
+    check_hostuser                 # find unprivileged host user                    # --hostuser
+    check_console                  # check if running on console
+    create_cachefiles              # create cache files owned by unprivileged user  # --cachebasedir
+    setup_verbosity                # create [and show] summary logfile              # --verbose
+    check_containeruser            # unprivileged user in container                 # --user
+    check_containerhomebasedir     # check base dir for --home and possible rootfs  # --homebasedir
 
   # Special x11docker jobs
-  [ "$Createlauncher" ] && {
-    create_launcher                                                               # --launcher: Create application launcher icon on desktop
-    finish
-  }
-  check_backend                                                                   # --backend
-  [ "$Installermode" ] && {                                                       # --install, --update, --update-master, --remove
-    case "$Packagedversion" in
-      yes)
-        case "$Installermode" in
-          --install|--update|--update-master|--remove|--remove-oldprefix)
-            error "Options --install|--update|--update-master|--remove
-  are not supported in packaged versions of x11docker.
-  Please use your package manager instead."
-          ;;
-        esac
-      ;;
-    esac
-    check_optionset "$Installermode" "$(grep -v -E -- '--install|--update|--update-master|--remove|--remove-oldprefix' <<< "$g_AllAvailableLongOptions")" ||:
-    installer "$Installermode"
-    finish
-  }
-  [ "$Cleanup" ] && {                                                             # --cleanup: Clean up cache and orphaned x11docker containers
-    check_optionset "--cleanup" "$(grep -v -E -- '--cleanup|--backend' <<< "$g_AllAvailableLongOptions")" ||:
-    cleanup
-    finish
-  }
+  if [ "$Createlauncher" ] ; then
+      # --launcher: Create application launcher icon on desktop
+      create_launcher
+      finish
+  fi
+
+  check_backend  # --backend
+
+  if [ "$Installermode" ] ; then
+      # --install, --update, --update-master, --remove
+      case "$Packagedversion" in
+          yes)
+              case "$Installermode" in
+                  --install|--update|--update-master|--remove|--remove-oldprefix)
+                      error "$(trim_to_bar \
+                        "|Options --install|--update|--update-master|--remove
+                         |  are not supported in packaged versions of x11docker.
+                         |  Please use your package manager instead." )"
+                      ;;
+              esac
+              ;;
+      esac
+      #
+      check_optionset \
+          "$Installermode" \
+          "$(grep -v -E -- '--install|--update|--update-master|--remove|--remove-oldprefix' <<< "$g_AllAvailableLongOptions")" \
+          || true
+      #
+      installer "$Installermode"
+      finish
+  fi
+
+  if [ "$Cleanup" ] ; then
+      # --cleanup: Clean up cache and orphaned x11docker containers
+      check_optionset \
+          "--cleanup" \
+          "$(grep -v -E -- '--cleanup|--backend' <<< "$g_AllAvailableLongOptions")" \
+          || true
+      #
+      cleanup
+      finish
+  fi
+
   if [ "$Buildimage" ] ; then
       # --build: Build image from x11docker repository
-      check_optionset "--build" "$(grep -v -E -- '--build|--backend' <<< "$g_AllAvailableLongOptions")" ||:
+      check_optionset \
+          "--build"   \
+          "$(grep -v -E -- '--build|--backend' <<< "$g_AllAvailableLongOptions")" \
+          || true
+      #
       buildimage "$g_Imagename"
       finish
   fi
+
   rocknroll || return 0
 
   setup_fifo                     # open message channels for container, xinitrc and watchpidlist()
