installer()

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -3372,30 +3372,30 @@ Keywords=docker x11docker $(echo "$Name" | tr -c '[:alpha:][:digit:][:blank:]' '
 }
 
 installer() {                   # --install, --update, --update-master, --remove: Installer for x11docker
-  # --install:
-  #   - copies x11docker to /usr/local/bin
-  #   - installs icon in /usr/share/icons
-  #   - creates x11docker.desktop file in /usr/share/applications
-  # --update:
-  #   - download and install latest release from github, regard existing installation location
-  # --update-master:
-  #   - download and install latest master version from github, regard existing installation location
-  # --remove
-  #   - remove installed files
+    # --install:
+    #   - copies x11docker to /usr/local/bin
+    #   - installs icon in /usr/share/icons
+    #   - creates x11docker.desktop file in /usr/share/applications
+    # --update:
+    #   - download and install latest release from github, regard existing installation location
+    # --update-master:
+    #   - download and install latest master version from github, regard existing installation location
+    # --remove
+    #   - remove installed files
 
-  ### FIXME: (--update)
-  ### maybe not install additional files if x11docker is owned by user
-  local Key1="" Key2="" Oldversion="" Newversion="" Format="" Prefix
+    ### FIXME: (--update)
+    ### maybe not install additional files if x11docker is owned by user
+    local Key1="" Key2="" Oldversion="" Newversion="" Format="" Prefix
 
-  Prefix="/usr/local"
+    Prefix="/usr/local"
 
-  case "${1:-}" in
-      --remove-oldprefix)
-          Prefix="/usr"
-          ;;
-      *)
-          if [ -x "/usr/bin/x11docker" ] ; then
-              warning "$(trim_to_bar \
+    case "${1:-}" in
+        --remove-oldprefix)
+            Prefix="/usr"
+            ;;
+        *)
+            if [ -x "/usr/bin/x11docker" ] ; then
+                warning "$(trim_to_bar \
                 "|Option ${1:-}: Detected x11docker installation in /usr/bin
                  |  Since version 7.6.0 x11docker defaults to ${Prefix}/bin instead.
                  |  If this was a custom installation without your package manager,
@@ -3405,57 +3405,67 @@ installer() {                   # --install, --update, --update-master, --remove
                  |rm    /usr/share/man/man1/x11docker.1.gz
                  |  or with x11docker option --remove-oldprefix"
                  )"
-              fi
-          ;;
-  esac
+            fi
+            ;;
+    esac
 
-  if [ "$Startuser" != "root" ] ; then
-      case "$Winsubsystem" in
-          CYGWIN|MSYS2) ;;
-          *)
-              case "$Installerarg" in
-                  diff) ;;
-                  *)
-                      error "Must run as root to install, update or remove x11docker system wide."
-                      return 1
-                      ;;
-              esac
-              ;;
-      esac
-  fi
+    if [ "$Startuser" != "root" ] ; then
+        case "$Winsubsystem" in
+            CYGWIN|MSYS2) ;;
+            *)
+                case "$Installerarg" in
+                    diff) ;;
+                    *)
+                        error "Must run as root to install, update or remove x11docker system wide."
+                        return 1
+                        ;;
+                esac
+                ;;
+        esac
+    fi
 
-  # Preparing
-  case "${1:-}" in
-    --install)
-      if [ ! -f "./x11docker" ]   ; then
-          error "$(trim_to_bar \
-           "|File x11docker not found in current folder.
-            |  Try 'x11docker --update' instead."
-            )"
-        return 1
-      fi
+    # Preparing
+    case "${1:-}" in
+        --install)
+            if [ ! -f "./x11docker" ]   ; then
+                error "$(trim_to_bar \
+                       "|File x11docker not found in current folder.
+                        |  Try 'x11docker --update' instead."
+                        )"
+                return 1
+            fi
 
-      [ -x "${Prefix}/bin/x11docker" ] && {
-        warning "x11docker seems to be installed already
-  at ${Prefix}/bin/x11docker.
-  Will overwrite existing installation.
-  Consider to use option '--update' or '--update-master' instead."
-      }
-    ;;
-    --update|--update-master)
-      [ -x "${Prefix}/bin/x11docker" ] && {
-        Oldversion="$(${Prefix}/bin/x11docker --version)"
-        note "Current installed version: x11docker $Oldversion
-  at ${Prefix}/bin/x11docker"
-      } || {
-        Oldversion=""
-      }
+            if [ -x "${Prefix}/bin/x11docker" ] ; then
+                warning "$(trim_to_bar \
+                         "|x11docker seems to be installed already
+                          |  at ${Prefix}/bin/x11docker.
+                          |  Will overwrite existing installation.
+                          |  Consider to use option '--update' or '--update-master' instead."
+                          )"
+            fi
+            ;;
+    
+        --update|--update-master)
+            if [ -x "${Prefix}/bin/x11docker" ] ; then
+                Oldversion="$(${Prefix}/bin/x11docker --version)"
+                note "$(trim_to_bar \
+              "|Current installed version: x11docker $Oldversion
+               |  at ${Prefix}/bin/x11docker"
+               )"
+            else
+                Oldversion=""
+            fi
 
-      [ -d     "/tmp/x11docker-install" ] && rm -R "/tmp/x11docker-install"
-      mkdir -p "/tmp/x11docker-install"   && cd    "/tmp/x11docker-install" || {
-        error "Could not create or cd to /tmp/x11docker-install."
-        return 1
-      }
+            if [ -d       "/tmp/x11docker-install" ] ; then  rm -R "/tmp/x11docker-install" ; fi
+            if ! mkdir -p "/tmp/x11docker-install" ; then
+                error "Could not create /tmp/x11docker-install."
+                return 1
+            fi
+            if ! cd    "/tmp/x11docker-install" ; then
+                error "Could not create or cd to /tmp/x11docker-install."
+                return 1
+            fi
+        
       download || {
         error "Neither wget nor curl found. Need 'wget' or 'curl' for download.
   Please install wget or curl."
