POST_CONDITION

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -712,6 +712,24 @@ SPY_STDOUT() {
     return "$exitCode"
 }
 
+# Function: POST_CONDITION
+# Usage: POST_CONDITION label condition
+#
+# Brief: Attempt to document possible values of a variable at some
+#        point.
+#
+if true ; then
+    # enforce postconditions
+    POST_CONDITION() {
+        if ! eval "$2" ; then
+            error "POST_CONDITION failed: '${1}' '${2}'"
+        fi
+    }
+else
+    # ignore postconditions
+    POST_CONDITION(){ : ; }
+fi
+
 # EndGroup: Debug_stuff
 
 # Function: usage
@@ -17099,32 +17117,35 @@ check_options_arguments() {
     grep -q -- "--runtime=crun"           <<< "$Customdockeroptions" && Runtime="crun"
     grep -q -- "--runtime=sysbox-runc"    <<< "$Customdockeroptions" && Runtime="sysbox-runc"
 
-    # --backend
-    if [ -z "$g_Imagename" ] ; then
-        case "${Cleanup},${Createlauncher},${Installermode}" in
-            ",,")
-                # Only create X server / --xonly  # BackendKind_host
-                Codename="xonly"
-                g_BackendKind="${g_BackendKind:-host}" # BackendKind_host
-                g_Containercommand="sleep infinity"
-                Showdisplayenvironment="${Showdisplayenvironment:-yes}"
+    # g_BackendKind : --backend
+    {
+        if [ -z "$g_Imagename" ] ; then
+            case "${Cleanup},${Createlauncher},${Installermode}" in
+                ",,")
+                    # Only create X server / --xonly  # BackendKind_host
+                    Codename="xonly"
+                    g_BackendKind="${g_BackendKind:-host}" # BackendKind_host
+                    g_Containercommand="sleep infinity"
+                    Showdisplayenvironment="${Showdisplayenvironment:-yes}"
+                    ;;
+            esac
+        fi
+
+        g_BackendKind="${g_BackendKind:-docker}"
+        case "$g_BackendKind" in
+            docker|podman|host) ;; # BackendKind_host
+            proot|nerdctl) 
+                note_ttm "|Option --backend=$g_BackendKind is deprecated.
+                          |  Please use --backend=docker or --backend=podman instead."
+                ;;
+            *) 
+                error "Option --backend: Unknown argument '$g_BackendKind'."
                 ;;
         esac
-    fi
+    }
+    POST_CONDITION g_BackendKind  'word_is_in "$g_BackendKind" "docker podman host proot nerdctl"'
 
-    g_BackendKind="${g_BackendKind:-docker}"
-    case "$g_BackendKind" in
-        docker|podman|host) ;; # BackendKind_host
-        proot|nerdctl) 
-            note_ttm "|Option --backend=$g_BackendKind is deprecated.
-                      |  Please use --backend=docker or --backend=podman instead."
-            ;;
-        *) 
-            error "Option --backend: Unknown argument '$g_BackendKind'."
-            ;;
-    esac
-
-    # --clipboard
+    # Shareclipboard : --clipboard
     case "$Shareclipboard" in
         yes|no|cmv|h2c|c2h) ;;
         superv|altv)
@@ -17151,6 +17172,7 @@ check_options_arguments() {
             Shareclipboard="no"
             ;;
     esac
+    POST_CONDITION Shareclipboard 'word_is_in "${Shareclipboard}" "yes no cmv h2c c2h"'
 
     # --dbus [=system]
     case "$Dbusrunsession" in
