indent

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -10615,6 +10615,9 @@ create_xinitrc() {
 
 
     if true ; then
+        #
+        # Note: Maybe it is too late here: paths are already embedded in commands. 
+        #
         trim_to_bar "|# Alternative coding for paths. Purpose: reduce diff between runs.
                      |Cachefolder='$Cachefolder'
                      |Sharefolder='$Sharefolder'
@@ -10662,177 +10665,182 @@ create_xinitrc() {
                  |Cookie=''
                  |Line=''
                  |Var=''
+                 |
                  |"
 
     echo               "echo 'Running xinitrc'"
     echo               "debugnote 'Running xinitrc'"
     echo               ""
 
-  case "$Xserver" in
-    --weston|--kwin|--hostwayland)
-      echo           "export $Newxenv"
-      echo           "unset  DISPLAY XAUTHORITY"
-      echo           "export DISPLAY XAUTHORITY"
-    ;;
-    --tty)
-      echo           "unset  DISPLAY XAUTHORITY WAYLAND_DISPLAY"
-      echo           "export DISPLAY XAUTHORITY WAYLAND_DISPLAY"
-    ;;
-    --runx)
-      [ "$Xauthentication" != "no" ] && {
-        echo         "# cookie generated by runx"
-        echo         'debugnote "xinitrc: Option --runx: Using cookie: $XAUTHORITY"'
-        echo         "cp -T -v \"\$XAUTHORITY\" '$Xclientcookie'"
-        echo         "cp -T -v \"\$XAUTHORITY\" '$Xservercookie'"
-      }
-      echo           "export $Newxenv"
-    ;;
-    *) # here something for real X servers
-      echo           "export $Newxenv"
-      case "$Xoverip" in
-        socat)
-          case "$Xcnetworkid" in
-            "")
-              echo "echo \"socat -d TCP-LISTEN:$((6000+Newdisplaynumber)),fork,bind=${Xcontainerip:-$Hostip} UNIX-CONNECT:$Newxsocket\""
-              echo        "socat -d TCP-LISTEN:$((6000+Newdisplaynumber)),fork,bind=${Xcontainerip:-$Hostip} UNIX-CONNECT:$Newxsocket &"
+    case "$Xserver" in
+        --weston|--kwin|--hostwayland)
+            echo           '# case "$Xserver" in --weston|--kwin|--hostwayland)'
+            echo           "export $Newxenv"
+            echo           "unset  DISPLAY XAUTHORITY"
+            echo           "export DISPLAY XAUTHORITY"
             ;;
-            *)
-              echo "echo \"socat -d TCP-LISTEN:$((6000+Newdisplaynumber)),fork,bind=$Xcontainername UNIX-CONNECT:$Newxsocket\""
-              echo        "socat -d TCP-LISTEN:$((6000+Newdisplaynumber)),fork,bind=$Xcontainername UNIX-CONNECT:$Newxsocket &"
+        --tty)
+            echo           '# case "$Xserver" in --tty)'
+            echo           "unset  DISPLAY XAUTHORITY WAYLAND_DISPLAY"
+            echo           "export DISPLAY XAUTHORITY WAYLAND_DISPLAY"
             ;;
-          esac
-          echo       "storepid \$! socat-tcp"
-        ;;
-      esac
-      echo           ""
-      case "$Xserver" in
-        --hostdisplay)
-          [ -s "$Hostxauthority" ] && {
-            echo     "# --hostdisplay: need cookie from host" ### FIXME rather get a trusted one
-            echo     "Hostcookie=\"\$(xauth -n -i -f $Hostxauthority list | grep :$Hostdisplaynumber | awk '{print \$3}')\""
-            echo     "xauth -n -i -f $Xclientcookie add $Newdisplay MIT-MAGIC-COOKIE-1 \$Hostcookie"
-            echo     ""
-          }
-        ;;
-        --nxagent)
-          echo       "sleep 1 && xsetroot -solid '#7F7F7F' 2>/dev/null &" ;;
-        *) echo      "xsetroot -solid '#7F7F7F' 2>/dev/null" ;;
-      esac
-      echo ""
+        --runx)
+            echo           '# case "$Xserver" in --runx)'
+            [ "$Xauthentication" != "no" ] && {
+                echo         "# cookie generated by runx"
+                echo         'debugnote "xinitrc: Option --runx: Using cookie: $XAUTHORITY"'
+                echo         "cp -T -v \"\$XAUTHORITY\" '$Xclientcookie'"
+                echo         "cp -T -v \"\$XAUTHORITY\" '$Xservercookie'"
+            }
+            echo           "export $Newxenv"
+            ;;
+        *) # here something for real X servers
+            echo           '# case "$Xserver" in *)'
+            echo           "export $Newxenv"
+            case "$Xoverip" in
+                socat)
+                    case "$Xcnetworkid" in
+                        "")
+                            echo "echo \"socat -d TCP-LISTEN:$((6000+Newdisplaynumber)),fork,bind=${Xcontainerip:-$Hostip} UNIX-CONNECT:$Newxsocket\""
+                            echo        "socat -d TCP-LISTEN:$((6000+Newdisplaynumber)),fork,bind=${Xcontainerip:-$Hostip} UNIX-CONNECT:$Newxsocket &"
+                            ;;
+                        *)
+                            echo "echo \"socat -d TCP-LISTEN:$((6000+Newdisplaynumber)),fork,bind=$Xcontainername UNIX-CONNECT:$Newxsocket\""
+                            echo        "socat -d TCP-LISTEN:$((6000+Newdisplaynumber)),fork,bind=$Xcontainername UNIX-CONNECT:$Newxsocket &"
+                            ;;
+                    esac
+                    echo       "storepid \$! socat-tcp"
+                    ;;
+            esac
+            echo           ""
+            case "$Xserver" in
+                --hostdisplay)
+                    [ -s "$Hostxauthority" ] && {
+                        echo     "# --hostdisplay: need cookie from host" ### FIXME rather get a trusted one
+                        echo     "Hostcookie=\"\$(xauth -n -i -f $Hostxauthority list | grep :$Hostdisplaynumber | awk '{print \$3}')\""
+                        echo     "xauth -n -i -f $Xclientcookie add $Newdisplay MIT-MAGIC-COOKIE-1 \$Hostcookie"
+                        echo     ""
+                    }
+                    ;;
+                --nxagent)
+                    echo       "sleep 1 && xsetroot -solid '#7F7F7F' 2>/dev/null &" ;;
+                *) echo      "xsetroot -solid '#7F7F7F' 2>/dev/null" ;;
+            esac
+            echo ""
 
-      [ "$Xauthentication" != "no" ] && {
-        echo         "# create new XAUTHORITY cookies"
-        case "$Xauthentication" in
-          yes|trusted)
-            Xauthentication="trusted"
-            echo     "Trusted=trusted"
-          ;;
-          untrusted)
-            echo     "Trusted=untrusted"
-          ;;
-        esac
-        echo         "echo \"Requesting \$Trusted cookie from X server\""
-        echo         "xauth -v -n -i -f $Xclientcookie generate $Newdisplay . \$Trusted timeout 3600"
-        [ "$Xserver" = '--hostdisplay' ] && {
-          echo       "[ -n \"\$Hostcookie\" ] && sed -i /\$Hostcookie/d $Xclientcookie"
-        }
-        echo         "[ -s '$Xclientcookie' ] || { "
-        echo         "  :"
-        case "$Xauthentication" in
-          untrusted)
+            [ "$Xauthentication" != "no" ] && {
+                echo         "# create new XAUTHORITY cookies"
+                case "$Xauthentication" in
+                    yes|trusted)
+                        Xauthentication="trusted"
+                        echo     "Trusted=trusted"
+                        ;;
+                    untrusted)
+                        echo     "Trusted=untrusted"
+                        ;;
+                esac
+                echo         "echo \"Requesting \$Trusted cookie from X server\""
+                echo         "xauth -v -n -i -f $Xclientcookie generate $Newdisplay . \$Trusted timeout 3600"
+                [ "$Xserver" = '--hostdisplay' ] && {
+                    echo       "[ -n \"\$Hostcookie\" ] && sed -i /\$Hostcookie/d $Xclientcookie"
+                }
+                echo         "[ -s '$Xclientcookie' ] || { "
+                echo         "  :"
+                case "$Xauthentication" in
+                    untrusted)
             echo     "  error '--xauth=untrusted: Failed to create cookie
   for untrusted clients.
   Maybe your X server misses extension SECURITY.'"
-          ;;
-        esac
-        echo         "}"
-        [ "$Xserver" = "--hostdisplay" ] && {
-          echo       "[ ! -s '$Xclientcookie' ] && {"
-          echo       "  [ -n \"\$Hostcookie\" ] && {"
-          echo       "    debugnote 'xinitrc() --hostdisplay: Failed to retrieve cookie from X server.
-  Maybe your X server misses extension SECURITY. Will bake one with host cookie.'"
-          echo       "    xauth -v -n -i -f $Xclientcookie add :$Newdisplaynumber . \$Hostcookie"
-          echo       "  }"
-          echo       "}"
-        }
-        echo         "[ -s '$Xclientcookie' ] || { "
-        echo         "  # still no cookie? try to create one without extension security"
-        echo         "  debugnote 'xinitrc(): Failed to retrieve trusted cookie from X server. Will bake one directly with xauth'"
-        echo         "  xauth -v -n -i -f $Xclientcookie add :$Newdisplaynumber . $(makecookie)"
-        echo         "}"
-        echo         "[ -s '$Xclientcookie' ] && {"
-        echo         "  # Prepare cookie with localhost identification disabled by ffff, needed if X socket is shared. ffff means 'familiy wild'"
-        echo         "  Cookie=\"\$(xauth -n -i -f $Xclientcookie nlist | sed -e 's/^..../ffff/')\""
-        echo         "  truncate -s0 $Xclientcookie"
-        echo         "  echo \"\$Cookie\" | xauth -v -n -i -f $Xclientcookie nmerge -"
-        echo         "}"
-        echo         "[ -s '$Xclientcookie' ] || {"
-        echo         "  debugnote 'xinitrc(): Failed to create cookie with xauth. Will try custom cookie baker script.'"
-        echo         "  cookiebaker '$Newdisplay' >> $Xclientcookie"
-        echo         "}"
-        echo         "ls -l $Xclientcookie"
-        echo         "truncate -s0 $Xservercookie"
-        echo         "cat $Xclientcookie >> $Xservercookie"
-        echo         "chmod 644 $Xclientcookie"
-        echo         ""
-        echo         "[ -s '$Xclientcookie' ] || error 'xinitrc(): Option --xauth=$Xauthentication: Cookie creation failed.'"
-      }
-      echo           "export XAUTHORITY=$Xclientcookie"
-      echo           "[ '$Xauthentication' = 'no' ] || [ ! -s '$Xclientcookie' ] && unset XAUTHORITY && warning 'Option --xauth=no: X server $Newdisplay runs without cookie authentication.'"
-      echo           ""
-      case "$Xserver" in
-        --hostdisplay) ;;   # do not change host settings
-        *)
-          case "$Xauthentication" in
-            yes|trusted|untrusted)
-              case "$Xserver" in
-                runx) ;;
-                *)
-                  echo "# clean xhost"
-                  echo "verbose 'Disabling any possible access to new X server possibly granted by xhost'"
-                  echo "disable_X_access_via_xhost"
-                ;;
-              esac
             ;;
-          esac
-          [ -n "$Xhost" ] && {
-            [ "$Xhost" = "auto" ] && Xhost="+SI:localuser:$Containeruser"
-            echo     "warning \"Option --xhost: Running 'xhost $Xhost' on $Newdisplay\""
-            echo     "xhost $Xhost"
-          }
-          echo       ""
-        ;;
-      esac
-
-      case "$Xserver" in
-        --hostdisplay|--nxagent) ;;
-        --hostwayland|--weston|--kwin|--tty) ;;
-        *)
-          echo       "# Keyboard layout"
-          [ -n "$Hostdisplay" ] && {
-            xtool --check setxkbmap && {
-              case "$Xkblayout" in
-                "") 
-                  #setxkbmap -display "$Hostdisplay" -print >> "$Xkbkeymapfile"
-                  echo "env DISPLAY=$Hostdisplay XAUTHORITY=$Hostxauthority setxkbmap -display $Hostdisplay -print >> $Xkbkeymapfile"
-                ;;
+                esac
+                echo         "}"
+                [ "$Xserver" = "--hostdisplay" ] && {
+                    echo       "[ ! -s '$Xclientcookie' ] && {"
+                    echo       "  [ -n \"\$Hostcookie\" ] && {"
+                    echo       "    debugnote 'xinitrc() --hostdisplay: Failed to retrieve cookie from X server.
+  Maybe your X server misses extension SECURITY. Will bake one with host cookie.'"
+                    echo       "    xauth -v -n -i -f $Xclientcookie add :$Newdisplaynumber . \$Hostcookie"
+                    echo       "  }"
+                    echo       "}"
+                }
+                echo         "[ -s '$Xclientcookie' ] || { "
+                echo         "  # still no cookie? try to create one without extension security"
+                echo         "  debugnote 'xinitrc(): Failed to retrieve trusted cookie from X server. Will bake one directly with xauth'"
+                echo         "  xauth -v -n -i -f $Xclientcookie add :$Newdisplaynumber . $(makecookie)"
+                echo         "}"
+                echo         "[ -s '$Xclientcookie' ] && {"
+                echo         "  # Prepare cookie with localhost identification disabled by ffff, needed if X socket is shared. ffff means 'familiy wild'"
+                echo         "  Cookie=\"\$(xauth -n -i -f $Xclientcookie nlist | sed -e 's/^..../ffff/')\""
+                echo         "  truncate -s0 $Xclientcookie"
+                echo         "  echo \"\$Cookie\" | xauth -v -n -i -f $Xclientcookie nmerge -"
+                echo         "}"
+                echo         "[ -s '$Xclientcookie' ] || {"
+                echo         "  debugnote 'xinitrc(): Failed to create cookie with xauth. Will try custom cookie baker script.'"
+                echo         "  cookiebaker '$Newdisplay' >> $Xclientcookie"
+                echo         "}"
+                echo         "ls -l $Xclientcookie"
+                echo         "truncate -s0 $Xservercookie"
+                echo         "cat $Xclientcookie >> $Xservercookie"
+                echo         "chmod 644 $Xclientcookie"
+                echo         ""
+                echo         "[ -s '$Xclientcookie' ] || error 'xinitrc(): Option --xauth=$Xauthentication: Cookie creation failed.'"
+            }
+            echo           "export XAUTHORITY=$Xclientcookie"
+            echo           "[ '$Xauthentication' = 'no' ] || [ ! -s '$Xclientcookie' ] && unset XAUTHORITY && warning 'Option --xauth=no: X server $Newdisplay runs without cookie authentication.'"
+            echo           ""
+            case "$Xserver" in
+                --hostdisplay) ;;   # do not change host settings
                 *)
-                  echo "setxkbmap '$Xkblayout' -print >> $Xkbkeymapfile"
-                ;;
-              esac
-            }
-            [ -s "$Xkbkeymapfile" ] && {
-              echo   "# set keyboard layout on $Newdisplay"
-              echo   "verbose \"Keyboard layout:"
-              echo   "\$(cat $Xkbkeymapfile)\""
-              echo   "xkbcomp $Xkbkeymapfile $Newdisplay"
-            }
-            echo     ""
-          }
-        ;;
-      esac
-    ;;
-  esac
+                    case "$Xauthentication" in
+                        yes|trusted|untrusted)
+                            case "$Xserver" in
+                                runx) ;;
+                                *)
+                                    echo "# clean xhost"
+                                    echo "verbose 'Disabling any possible access to new X server possibly granted by xhost'"
+                                    echo "disable_X_access_via_xhost"
+                                    ;;
+                            esac
+                            ;;
+                    esac
+                    [ -n "$Xhost" ] && {
+                        [ "$Xhost" = "auto" ] && Xhost="+SI:localuser:$Containeruser"
+                        echo     "warning \"Option --xhost: Running 'xhost $Xhost' on $Newdisplay\""
+                        echo     "xhost $Xhost"
+                    }
+                    echo       ""
+                    ;;
+            esac
+
+            case "$Xserver" in
+                --hostdisplay|--nxagent) ;;
+                --hostwayland|--weston|--kwin|--tty) ;;
+                *)
+                    echo       "# Keyboard layout"
+                    [ -n "$Hostdisplay" ] && {
+                        xtool --check setxkbmap && {
+                            case "$Xkblayout" in
+                                "") 
+                                    #setxkbmap -display "$Hostdisplay" -print >> "$Xkbkeymapfile"
+                                    echo "env DISPLAY=$Hostdisplay XAUTHORITY=$Hostxauthority setxkbmap -display $Hostdisplay -print >> $Xkbkeymapfile"
+                                    ;;
+                                *)
+                                    echo "setxkbmap '$Xkblayout' -print >> $Xkbkeymapfile"
+                                    ;;
+                            esac
+                        }
+                        [ -s "$Xkbkeymapfile" ] && {
+                            echo   "# set keyboard layout on $Newdisplay"
+                            echo   "verbose \"Keyboard layout:"
+                            echo   "\$(cat $Xkbkeymapfile)\""
+                            echo   "xkbcomp $Xkbkeymapfile $Newdisplay"
+                        }
+                        echo     ""
+                    }
+                    ;;
+            esac
+            ;;
+    esac
 
   case "$Xserver" in
     --xpra|--xpra2|--xvfb|--weston-xwayland|--xwayland)
