use if-then-else in alertbox()

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -494,27 +494,23 @@ alertbox() {                    # X alert box with title $1 and message $2
   Message="$(echo "$Message" | LANG=C sed "s/[\x80-\xFF]//g" | fold -w120 )"
 
   # try some tools to show alert message. If all tools fail, return 1
-  command -v   xmessage     >/dev/null && [ -n "${DISPLAY:-}" ] && {
-      printf "%s\n\n%s" "${Title}" "${Message}"  \
-          | xmessage  -file - -default okay      \
-          || true
-  } || {
-      command -v gxmessage    >/dev/null && [ -n "${DISPLAY:-}" ] && {
+  if [ -n "${DISPLAY:-}" ] ; then
+      if command -v   xmessage     >/dev/null ; then
+          printf "%s\n\n%s" "${Title}" "${Message}"  \
+              | xmessage  -file - -default okay      \
+              || true
+      elif command -v gxmessage    >/dev/null ; then
           printf "%s\n\n%s" "${Title}" "${Message}"  \
               | gxmessage -file - -default okay      \
               || true
-      }
-  } || {
-      command -v zenity       >/dev/null && [ -n "${DISPLAY:-}" ] && {
+      elif command -v zenity       >/dev/null ; then
           zenity --error --no-markup --ellipsize \
                  --title="$Title"                \
                  --text="$Message"               \
                  2>/dev/null                     \
               || true
-      }
-  } || {
-      # shellcheck disable=SC2001
-      command -v yad          >/dev/null && [ -n "${DISPLAY:-}" ] && {
+      elif command -v yad          >/dev/null ; then
+          # shellcheck disable=SC2001
           yad  --image "dialog-error" \
                --title "$Title"       \
                --button=gtk-ok:0      \
@@ -522,29 +518,29 @@ alertbox() {                    # X alert box with title $1 and message $2
                --fixed                \
                2>/dev/null            \
               || true
-      }
-  } || {
-      command -v kdialog      >/dev/null && [ -n "${DISPLAY:-}" ] && {
+      elif command -v kdialog      >/dev/null ; then
           # shellcheck disable=SC2001
           kdialog                                               \
               --title "$Title"                                  \
               --error "$(echo "$Message" | sed 's/\\/\\\\/g' )" \
               2>/dev/null                                       \
               || true
-    }
-  } || {
-      command -v xterm        >/dev/null && [ -n "${DISPLAY:-}" ] && {
+      elif command -v xterm        >/dev/null ; then
           # shellcheck disable=SC2001
           xterm                             \
               -title "$Title"               \
               -e "echo '$(echo "$Message" | sed "s/'/\"/g")' ; read -n1" \
               || true
-      }
-  } || {
+      else
+          # none of the abve branches matched
+          false
+      fi
+  fi || {
+      # Try  notify-send with or without DISPLAY
       notify-send "$(printf "%s\n\n%s" "${Title}" "${Message}" )"  2>/dev/null
   } || {
-    warning "$(printf "Could not display message on X:\n%s" "$Message" )"
-    return 1
+      warning "$(printf "Could not display message on X:\n%s" "$Message" )"
+      return 1
   }
   return 0
 }
