use heredoc for python version of parse_inspect()

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -1282,7 +1282,65 @@ parse_inspect() {               # parse json of inspect output using python
       return
   }
 
-  Parserscript="#! $Pythonbin"$'
+  ##   ##
+  ##   ## Another $'string' here
+  ##   ##
+  ##   Parserscript="#! $Pythonbin"$'
+  ## import json,sys
+  ## 
+  ## def parse_inspect(*args):
+  ##     """
+  ##     parse output of docker|podman|nerdctl inspect
+  ##     args:
+  ##      0: ignored
+  ##      1: string containing inspect output
+  ##      2..n: json keys. For second level keys provide e.g. "Config","Cmd"
+  ##     Prints key value as a string.
+  ##     Prints empty string if key not found.
+  ##     A list is printed as a string with \'\' around each element.
+  ##     """
+  ## 
+  ##     output=""
+  ##     inspect=args[1]
+  ##     inspect=inspect.strip()
+  ## 
+  ##     obj=json.loads(inspect)
+  ## 
+  ##     if "\'list\'" in str(type(obj)):
+  ##         obj = obj[0]
+  ## 
+  ##     for arg in args[2:]: # recursively find the desired object. Command.Cmd is found with args "Command" , "Cmd"
+  ##         try:
+  ##             obj=obj[arg]
+  ##         except:
+  ##             obj=""
+  ## 
+  ##     objtype=str(type(obj))
+  ##     if "\'list\'" in objtype:
+  ##         for i in obj:
+  ##             output += "\'" + str(i) + "\' "
+  ##         output = output.strip()
+  ##     else:
+  ##         output = str(obj)
+  ## 
+  ##     if output == "None":
+  ##         output=""
+  ## 
+  ##     print(output)
+  ## 
+  ## parse_inspect(*sys.argv)
+  ## '
+  ## ## end of $'string' here
+  ## ##
+  ##   echo "$Parserscript" | $Pythonbin - "$@" || warning "parse_inspect(): Error while parsing json for
+  ##   ${2:-} ${3:-} ${4:-} ${5:-} ${6:-} (Line $BASH_LINENO)"
+  ##
+  #
+  # Replacement using heredoc.
+  #
+  {
+      echo "#! $Pythonbin"
+      cat <<"END"
 import json,sys
 
 def parse_inspect(*args):
@@ -1294,7 +1352,7 @@ def parse_inspect(*args):
      2..n: json keys. For second level keys provide e.g. "Config","Cmd"
     Prints key value as a string.
     Prints empty string if key not found.
-    A list is printed as a string with \'\' around each element.
+    A list is printed as a string with '' around each element.
     """
 
     output=""
@@ -1303,7 +1361,7 @@ def parse_inspect(*args):
 
     obj=json.loads(inspect)
 
-    if "\'list\'" in str(type(obj)):
+    if "'list'" in str(type(obj)):
         obj = obj[0]
 
     for arg in args[2:]: # recursively find the desired object. Command.Cmd is found with args "Command" , "Cmd"
@@ -1313,9 +1371,9 @@ def parse_inspect(*args):
             obj=""
 
     objtype=str(type(obj))
-    if "\'list\'" in objtype:
+    if "'list'" in objtype:
         for i in obj:
-            output += "\'" + str(i) + "\' "
+            output += "'" + str(i) + "' "
         output = output.strip()
     else:
         output = str(obj)
@@ -1326,9 +1384,10 @@ def parse_inspect(*args):
     print(output)
 
 parse_inspect(*sys.argv)
-'
-  echo "$Parserscript" | $Pythonbin - "$@" || warning "parse_inspect(): Error while parsing json for
+END
+  } | $Pythonbin - "$@" || warning "parse_inspect(): Error while parsing json for
   ${2:-} ${3:-} ${4:-} ${5:-} ${6:-} (Line $BASH_LINENO)"
+
 }
 
 
