setup_sound_pipewire(), setup_sound_pulseaudio()

diff --git a/x11docker b/x11docker
--- a/x11docker
+++ b/x11docker
@@ -4756,143 +4756,221 @@ setup_sound_alsa() {
   return 0
 }
 
-setup_sound_pipewire() {        # option --pipewire: pipewire sound in container
-  local Pipewiresocket Pipewirescript
+#
+# function setup_sound_pipewire() : option --pipewire: pipewire sound
+#                                   in container
+#
+setup_sound_pipewire() {
 
-  command -v pw-container >/dev/null || {
-    note "Option --pipewire: Command pw-container not found.
-  Is pipewire installed on your system?
-  Fallback: Disabling option --pipewire
-  You can try options --pulseaudio or --alsa instead."
-    check_fallback
-    Sharepipewire="no"
-    return 1
-  }
+    local Pipewiresocket Pipewirescript
 
-  warning "Option --pipewire allows container applications
-  to catch your audio output and microphone input."
-
-  # create and share restricted pipewire socket
-  Pipewirescript="$Cachefolder/pw-script"
-  echo "#! /bin/bash
-# helper script to get socket path. Reading output of pw-container directly somehow not possible.
-echo \$PIPEWIRE_REMOTE >$Cachefolder/PIPEWIRE_REMOTE
-while :; do
-  sleep 1000
-done
-" >"$Pipewirescript"
-  unpriv "pw-container 'bash $Pipewirescript'" &
-  storepid $! "pw-container"
-  Pipewiresocket="$(cat "$Cachefolder/PIPEWIRE_REMOTE")"
-  Pipewiresocket="/$(echo "$Pipewiresocket" | cut -d/ -f2-)"
-  store_runoption_env "PIPEWIRE_REMOTE=$Pipewiresocket"
-  store_runoption_volume "$Pipewiresocket"
-
-  # share pulseaudio socket created by pipewire
-  command -v pactl >/dev/null && {
-    Pipewirepulseaudiosocket="$(unpriv "env LC_ALL=C pactl info" 2>/dev/null)"
-    Pipewirepulseaudiosocket="/$(grep "Server String" <<< "$Pipewirepulseaudiosocket" | cut -d/ -f2-)"
-    [ -z "$Pipewirepulseaudiosocket" ] && {
-      [ -e "/run/user/$Hostuseruid/pulse/native" ] && Pipewirepulseaudiosocket="/run/user/$Hostuseruid/pulse/native"
+    command -v pw-container >/dev/null || {
+        note "$(trim_to_bar \
+          "|Option --pipewire: Command pw-container not found.
+           |  Is pipewire installed on your system?
+           |  Fallback: Disabling option --pipewire
+           |  You can try options --pulseaudio or --alsa instead."
+           )"
+        check_fallback
+        Sharepipewire="no"
+        return 1
     }
-  }
-  [ -z "$Pipewirepulseaudiosocket" ] && note "Option --pipewire: Did not find pulseaudio socket.
-  Are 'pipewire-module-pulse' and 'pactl' installed?
-  Fallback: Not sharing pipewire pulseaudio scoket."
+
+    warning "$(trim_to_bar \
+       "|Option --pipewire allows container applications
+        |  to catch your audio output and microphone input."
+        )"
+
+    # Create and share restricted pipewire socket
+    Pipewirescript="$Cachefolder/pw-script"
+    trim_to_bar \
+        "|#! /bin/bash
+         |# Helper script to get socket path.
+         |# Reading output of pw-container directly somehow not possible.
+         |
+         |echo \$PIPEWIRE_REMOTE >$Cachefolder/PIPEWIRE_REMOTE
+         |while :; do
+         |  sleep 1000
+         |done
+         |" >"$Pipewirescript"
+
+    unpriv "pw-container 'bash $Pipewirescript'" &
+    storepid $! "pw-container"
+
+    Pipewiresocket="$(cat "$Cachefolder/PIPEWIRE_REMOTE")"
+    Pipewiresocket="/$(echo "$Pipewiresocket" | cut -d/ -f2-)"
+    store_runoption_env "PIPEWIRE_REMOTE=$Pipewiresocket"
+    store_runoption_volume "$Pipewiresocket"
+
+    # Share pulseaudio socket created by pipewire
+    if command -v pactl >/dev/null ; then
+        Pipewirepulseaudiosocket="$(unpriv "env LC_ALL=C pactl info" 2>/dev/null)"
+        Pipewirepulseaudiosocket="/$(grep "Server String" <<< "$Pipewirepulseaudiosocket" | cut -d/ -f2-)"
+        if [ -z "$Pipewirepulseaudiosocket" ] ; then
+            if [ -e "/run/user/$Hostuseruid/pulse/native" ] ; then
+                Pipewirepulseaudiosocket="/run/user/$Hostuseruid/pulse/native"
+            fi
+        fi
+    fi
+
+    if [ -z "$Pipewirepulseaudiosocket" ] ; then
+        note "$(trim_to_bar \
+           "|Option --pipewire: Did not find pulseaudio socket.
+            |  Are 'pipewire-module-pulse' and 'pactl' installed?
+            |  Fallback: Not sharing pipewire pulseaudio scoket."
+            )"
+    fi
 }
 
-setup_sound_pulseaudio() {      # option --pulseaudio: set up pulseaudio connection
-  # Allowing container access to Pulseaudio on host can be done with a shared socket or over TCP.
-  # Sharing host user socket in XDG_RUNTIME_DIR fails since Pulseaudio v12.0.
-  # Instead, a new socket is created with pactl.
-  # TCP module is created after container startup to authenticate it with container IP.
-  # Detailed documentation at: https://github.com/mviereck/x11docker/wiki/Container-sound:-ALSA-or-Pulseaudio
-  #
-  # g  $Pulseaudiomode    =tcp or =socket or=host: Connect over tcp or with shared socket
-  # g  $Pulseaudioport    TCP port
-  local Lowerport= Upperport= Setcookie=
+# function setup_sound_pulseaudio() : option --pulseaudio: set up
+#                                     pulseaudio connection
+#
+setup_sound_pulseaudio() {
+    #
+    # Allowing container access to Pulseaudio on host can be done with
+    # a shared socket or over TCP.
+    #
+    # Sharing host user socket in XDG_RUNTIME_DIR fails since
+    # Pulseaudio v12.0.
+    #
+    # Instead, a new socket is created with pactl.
+    #
+    # TCP module is created after container startup to authenticate it
+    # with container IP.
+    #
+    # Detailed documentation at:
+    # https://github.com/mviereck/x11docker/wiki/Container-sound:-ALSA-or-Pulseaudio
+    #
+    # g $Pulseaudiomode =tcp or =socket or =host: Connect over tcp or
+    #                                             with shared socket
+    #
+    # g  $Pulseaudioport    TCP port
+    #
+    local Lowerport= Upperport= Setcookie=
 
-  command -v pactl >/dev/null || {
-    note "Option --pulseaudio: pactl not found.
-  Is pulseaudio installed and running on your host system?
-  Fallback: Disabling option --pulseaudio.
-  You can try options --pipewire or --alsa instead."
-    check_fallback
-    Pulseaudiomode=""
-    return 1
-  }
-
-  [ -z "$Pulseaudiomode" ] && Pulseaudiomode="socket"
-  [ "$Pulseaudiomode" = "auto" ] && {
-    Pulseaudiomode="socket"
-    [ "$Containeruser" = "$Hostuser" ]                        || Pulseaudiomode="tcp"
-    [ "$Runtime" = "kata-runtime" ]                           && Pulseaudiomode="tcp"
-    [ "$Runtime" = "sysbox-runc" ]                            && Pulseaudiomode="tcp"
-    [ "$Snapsupport" = "yes" ]                                && Pulseaudiomode="tcp"
-    unpriv 'LC_ALL=C pactl info | grep -q "User Name: pulse"' && Pulseaudiomode="tcp"
-    [ "$Pulseaudiomode" = "tcp" ] && note "Option --pulseaudio: Enabling TCP mode"
-  }
-
-  [ "$Pulseaudiomode" = "tcp" ] && [ "$g_Network" = "none" ] && {
-    note "Option --pulseaudio: Without option -I, --network
-  pulseaudio sound over TCP is not possible but needed in your setup.
-  Fallback: Disabling option --pulseaudio."
-    Pulseaudiomode=""
-    check_fallback
-    return 1
-  }
-
-  warning "Option --pulseaudio allows container applications
-  to catch your audio output and microphone input."
-
-  case "$Pulseaudiomode" in
-    socket|tcp)
-      grep -q -i "PipeWire" <<< "$(unpriv "pactl info")" && note "Option --pulseaudio: Found pipewire sound server.
-  If pulseaudio sound fails, you can try 
-  --pipewire, --pulseaudio=tcp or --pulseaudio=host instead."
-    ;;
-  esac
-  
-  case "$Pulseaudiomode" in
-    socket)
-      # create pulseaudio socket
-      Pulseaudiomoduleid="$(unpriv "pactl load-module module-native-protocol-unix socket='$Pulseaudiosocket' 2>&1 ||:")"
-      #Pulseaudiomoduleid="$(unpriv "pactl load-module libpipewire-module-protocol-native socket='$Pulseaudiosocket' 2>&1 ||:")" # fails with pipewire
-
-      isint "$Pulseaudiomoduleid" && {
-        storeinfo_add_kv_sh "pulseaudiomoduleid=$Pulseaudiomoduleid"
-        store_runoption_env "PULSE_SERVER=unix:$(convertpath share "$Pulseaudiosocket")"
-        Setcookie="yes"
-      } || {
-        note "Option --pulseaudio: command pactl failed with output:
-  '$Pulseaudiomoduleid'
-  Is pulseaudio running at all on your host?
-  Fallback: Disabling option --pulseaudio.
-  You can try options --pipewire or --alsa instead."
+    if ! command -v pactl >/dev/null ; then
+        note "$(trim_to_bar \
+           "|Option --pulseaudio: pactl not found.
+            |  Is pulseaudio installed and running on your host system?
+            |  Fallback: Disabling option --pulseaudio.
+            |  You can try options --pipewire or --alsa instead."
+            )"
         check_fallback
         Pulseaudiomode=""
         return 1
-      }
+    fi
 
-      echo "# Connect to host pulseaudio server using mounted UNIX socket
-default-server = unix:$(convertpath share "$Pulseaudiosocket")
-# Prevent a server running in container
-autospawn = no
-daemon-binary = /bin/true
-# Prevent use of shared memory
-enable-shm = false
-" >> "$Pulseaudioconf"
-        verbose "Generated pulseaudio client.conf:
-$(nl -ba < "$Pulseaudioconf")"
-    ;;
-    tcp)
-      read Lowerport Upperport < /proc/sys/net/ipv4/ip_local_port_range 2>/dev/null
-      [ "$Lowerport" ] || Lowerport=33000
-      [ "$Upperport" ] || Upperport=60000
-      while : ; do
-        Pulseaudioport="$(shuf -i $Lowerport-$Upperport -n1)"
-        ss -lpn | grep -q ":$Pulseaudioport " || break
-      done
+    if [ -z "$Pulseaudiomode" ] ; then
+        Pulseaudiomode="socket"
+    fi
+
+    if [ "$Pulseaudiomode" = "auto" ] ; then
+        Pulseaudiomode="socket"
+        #
+        # Adjustments, only if "auto"
+        #
+        if [ "$Containeruser" != "$Hostuser" ] ; then
+            Pulseaudiomode="tcp"
+        fi
+        #
+        if [ "$Runtime" = "kata-runtime" ] ; then
+            Pulseaudiomode="tcp"
+        fi
+        #
+        if [ "$Runtime" = "sysbox-runc" ] ; then
+            Pulseaudiomode="tcp"
+        fi
+        #
+        if [ "$Snapsupport" = "yes" ] ; then
+            Pulseaudiomode="tcp"
+        fi
+        #
+        if unpriv 'LC_ALL=C pactl info | grep -q "User Name: pulse"' ; then
+            Pulseaudiomode="tcp"
+        fi
+        #
+        if [ "$Pulseaudiomode" = "tcp" ] ; then
+            note "Option --pulseaudio: Enabling TCP mode"
+        fi
+    fi
+
+    if [ "$Pulseaudiomode" = "tcp" ] && [ "$g_Network" = "none" ] ; then
+        note "$(trim_to_bar \
+           "|Option --pulseaudio: Without option -I, --network
+            |  pulseaudio sound over TCP is not possible but needed in your setup.
+            |  Fallback: Disabling option --pulseaudio."
+            )"
+        #
+        Pulseaudiomode=""
+        check_fallback
+        return 1
+    fi
+
+    warning "$(trim_to_bar \
+         "|Option --pulseaudio allows container applications
+          |  to catch your audio output and microphone input."
+          )"
+
+    case "$Pulseaudiomode" in
+        socket|tcp)
+            if grep -q -i "PipeWire" <<< "$(unpriv "pactl info")" ; then
+                note "$(trim_to_bar \
+                  "|Option --pulseaudio: Found pipewire sound server.
+                   |  If pulseaudio sound fails, you can try
+                   |  --pipewire, --pulseaudio=tcp or --pulseaudio=host instead."
+                   )"
+            fi
+            ;;
+    esac
+
+    case "$Pulseaudiomode" in
+        socket)
+            # Create pulseaudio socket
+            Pulseaudiomoduleid="$(
+                unpriv "pactl load-module module-native-protocol-unix        socket='$Pulseaudiosocket' 2>&1 ||:"
+            )"
+            # Pulseaudiomoduleid="$(
+            #   unpriv "pactl load-module libpipewire-module-protocol-native socket='$Pulseaudiosocket' 2>&1 ||:"
+            # )" # fails with pipewire
+
+            if isint "$Pulseaudiomoduleid" ; then
+                storeinfo_add_kv_sh "pulseaudiomoduleid=$Pulseaudiomoduleid"
+                store_runoption_env "PULSE_SERVER=unix:$(convertpath share "$Pulseaudiosocket")"
+                Setcookie="yes"
+            else
+                note "$(trim_to_bar \
+                  "|Option --pulseaudio: command pactl failed with output:
+                   |  '$Pulseaudiomoduleid'
+                   |  Is pulseaudio running at all on your host?
+                   |  Fallback: Disabling option --pulseaudio.
+                   |  You can try options --pipewire or --alsa instead."
+                   )"
+                check_fallback
+                Pulseaudiomode=""
+                return 1
+            fi
+
+            trim_to_bar \
+                "|# Connect to host pulseaudio server using mounted UNIX socket
+                 |default-server = unix:$(convertpath share "$Pulseaudiosocket")
+                 |# Prevent a server running in container
+                 |autospawn = no
+                 |daemon-binary = /bin/true
+                 |# Prevent use of shared memory
+                 |enable-shm = false
+                 |" >> "$Pulseaudioconf"
+            verbose "Generated pulseaudio client.conf:${NEWLINE}$(nl -ba < "$Pulseaudioconf")"
+            ;;
+
+        tcp)
+            read Lowerport Upperport < /proc/sys/net/ipv4/ip_local_port_range 2>/dev/null
+            [ "$Lowerport" ] || Lowerport=33000
+            [ "$Upperport" ] || Upperport=60000
+            while : ; do
+                Pulseaudioport="$(shuf -i $Lowerport-$Upperport -n1)"
+                ss -lpn | grep -q ":$Pulseaudioport " || break
+            done
+
       [ -e "$Hostuserhome/.config/pulse/cookie" ] && cp "$Hostuserhome/.config/pulse/cookie" "$Pulseaudiocookie" || note "Option --pulseaudio: Did not find cookie
   $Hostuserhome/.config/pulse/cookie"
       store_runoption_env "PULSE_SERVER=tcp:$Hostip:$Pulseaudioport"
